import { test, expect } from '@playwright/test'
import { dismissTour, launchApp, resizeWindow, seedBook } from './harness'

test('focus keeps the page, caret and split layout while its tools are tucked away', async () => {
  const h = await launchApp('nl-focus-')
  try {
    const book = await seedBook(h, { Chapter: ['Opening', 'Reference'] })
    await dismissTour(h.page)
    await resizeWindow(h, 1300, 900)
    await h.page.evaluate(async (chapter) => {
      const project = window.novalistStores.project.getState()
      await project.openScene(chapter.guid, chapter.scenes[0].id)
      await project.openSceneInSplit(chapter.guid, chapter.scenes[1].id)
    }, book.chapters[0])
    const frame = h.page.frameLocator('iframe.editor-frame').last()
    const editor = frame.locator('#editor')
    await expect(editor).toBeVisible()
    await editor.click()
    await h.page.keyboard.type('A quiet page')
    const paneTree = await h.page.evaluate(() => JSON.stringify(window.novalistStores.shell.getState().panes))
    // A property on the iframe proves it survives both focus and navigation.
    await editor.evaluate((element) => { element.dataset.focusProbe = 'same-editor' })
    await h.page.keyboard.press('F11')
    await expect(h.page.locator('.shell-focus')).toBeVisible()
    await expect(h.page.locator('.editor-toolbar-primary:visible')).toHaveCount(0)
    await expect(h.page.locator('.pane-header:visible')).toHaveCount(0)
    await expect(h.page.locator('iframe.editor-frame:visible')).toHaveCount(1)
    await h.page.keyboard.type(' keeps its caret.')
    await expect(editor).toHaveText('A quiet page keeps its caret.')
    await h.page.evaluate(() => window.novalistStores.shell.getState().setSuggestionMode(true))
    await expect(h.page.locator('.editor-mode-bar:visible')).toHaveCount(1)
    await expect(h.page.locator('.editor-toolbar-primary:visible')).toHaveCount(0)
    await h.page.evaluate(() => window.novalistStores.shell.getState().setSuggestionMode(false))
    await h.page.screenshot({ path: 'test-results/focus-page.png' })

    const before = await h.page.locator('iframe.editor-frame:visible').boundingBox()
    await h.page.keyboard.press('Control+Shift+n')
    const notes = h.page.getByRole('dialog', { name: 'Synopsis and notes' })
    await expect(notes).toBeVisible()
    const after = await h.page.locator('iframe.editor-frame:visible').boundingBox()
    expect(after).toEqual(before)
    await notes.locator('#dock-synopsis').fill('Keep the secret until the end.')
    await notes.getByRole('button', { name: 'Return to writing' }).click()
    await expect(notes).toHaveCount(0)
    await expect(editor).toBeFocused()
    await h.page.keyboard.type(' Still here.')
    await expect(editor).toContainText('caret. Still here.')
    await expect.poll(() => h.rpc<{ synopsis: string }>('scenes/getMeta', [book.chapters[0].guid, book.chapters[0].scenes[1].id]).then((s) => s.synopsis))
      .toBe('Keep the secret until the end.')

    await h.page.keyboard.press('Control+Shift+n')
    await notes.locator('#dock-synopsis').fill('Saved with Escape.')
    await h.page.keyboard.press('Escape')
    await expect(notes).toHaveCount(0)
    await expect.poll(() => h.rpc<{ synopsis: string }>('scenes/getMeta', [book.chapters[0].guid, book.chapters[0].scenes[1].id]).then((s) => s.synopsis))
      .toBe('Saved with Escape.')
    await h.page.keyboard.press('Control+Shift+n')
    await notes.locator('#dock-synopsis').fill('Saved with the toggle shortcut.')
    await h.page.keyboard.press('Control+Shift+n')
    await expect(notes).toHaveCount(0)
    await expect.poll(() => h.rpc<{ synopsis: string }>('scenes/getMeta', [book.chapters[0].guid, book.chapters[0].scenes[1].id]).then((s) => s.synopsis))
      .toBe('Saved with the toggle shortcut.')

    await h.page.keyboard.press('Control+Alt+b')
    await expect(h.page.getByRole('dialog', { name: 'Chapters and scenes' })).toBeVisible()
    await h.page.keyboard.press('Escape')
    await expect(h.page.locator('.focus-panel-open')).toHaveCount(0)
    await h.page.keyboard.press('Control+Alt+i')
    await expect(h.page.getByRole('dialog', { name: 'Scene context' })).toBeVisible()
    await h.page.keyboard.press('Escape')

    await h.page.evaluate(() => window.novalistStores.shell.getState().setMainView('codex'))
    await expect(h.page.getByRole('button', { name: 'Return to the page' })).toBeVisible()
    await h.page.getByRole('button', { name: 'Return to the page' }).click()
    await expect(editor).toHaveAttribute('data-focus-probe', 'same-editor')
    await expect(editor).toBeFocused()
    await h.page.keyboard.type(' Back again.')
    await expect(editor).toContainText('Still here. Back again.')

    await h.page.locator('.focus-reveal').click()
    // Finish the editor's pending notification after focus moved to the tools.
    // It must not hide the button the writer is about to use.
    await editor.evaluate((element) => {
      const frameWindow = element.ownerDocument.defaultView as unknown as { flushPendingContentChange(): void }
      frameWindow.flushPendingContentChange()
    })
    await expect(h.page.getByRole('button', { name: 'Leave focus' })).toBeVisible()
    await h.page.getByRole('button', { name: 'Leave focus' }).click()
    await expect(h.page.locator('iframe.editor-frame:visible')).toHaveCount(2)
    expect(await h.page.evaluate(() => JSON.stringify(window.novalistStores.shell.getState().panes))).toBe(paneTree)
    await expect(editor).toHaveAttribute('data-focus-probe', 'same-editor')
  } finally { await h.close() }
})

test('project shelves show their books, support search, moving and survive a restart', async () => {
  const h = await launchApp('nl-library-')
  try {
    await h.rpc('project/create', [h.workDir, 'The Northern Cycle', 'Winter Letters'])
    await h.rpc('project/createBook', ['The Thaw'])
    await h.rpc('project/create', [h.workDir, 'Orchard Notes', 'A Small Harvest'])
    await h.page.evaluate(() => window.novalistStores.project.getState().closeProject())
    await h.page.evaluate(() => window.novalistStores.project.getState().loadRecents())
    await dismissTour(h.page)
    await resizeWindow(h, 1300, 900)
    await expect(h.page.locator('.start-recent-card')).toHaveCount(3)
    await expect(h.page.locator('.volume-name')).toHaveText(['A Small Harvest', 'Winter Letters', 'The Thaw'])
    await expect(h.page.getByText('2 books · World Bible')).toBeVisible()
    await h.page.screenshot({ path: 'test-results/project-library.png' })
    const volumes = h.page.locator('.project-volume')
    const northern = volumes.filter({ has: h.page.getByRole('button', { name: 'Open The Northern Cycle' }) })
    const orchard = volumes.filter({ has: h.page.getByRole('button', { name: 'Open Orchard Notes' }) })
    await northern.dragTo(orchard)
    await expect(volumes.first().locator('.start-recent-name')).toHaveText('The Northern Cycle')
    await northern.getByRole('button', { name: 'Move The Northern Cycle later' }).click()
    await expect(volumes.first().locator('.start-recent-name')).toHaveText('Orchard Notes')
    await h.page.getByRole('button', { name: 'Add shelf', exact: true }).click()
    await h.page.getByRole('textbox', { name: 'Shelf name', exact: true }).fill('Working drafts')
    await h.page.getByRole('button', { name: 'Create shelf', exact: true }).click()
    const shelf = h.page.getByRole('region', { name: 'Working drafts', exact: true })
    await shelf.getByRole('button', { name: 'Move shelf up', exact: true }).click()
    await expect(h.page.locator('.project-shelf').first()).toHaveAttribute('aria-label', 'Working drafts')
    await expect(shelf.getByRole('button', { name: 'Move shelf up', exact: true })).toBeDisabled()
    await expect(h.page.getByRole('region', { name: 'My projects', exact: true }).getByRole('button', { name: 'Move shelf up', exact: true })).toBeEnabled()
    await h.page.getByRole('combobox', { name: 'Shelf for The Northern Cycle' }).selectOption({ label: 'Working drafts' })
    await expect(shelf.getByRole('button', { name: 'Open The Northern Cycle' })).toBeVisible()
    // Keep both native drag targets in view; Playwright scrolls before mousedown.
    await resizeWindow(h, 1300, 1500)
    await orchard.locator('.volume-cover').dragTo(shelf.locator('.project-shelf-heading'))
    await expect(shelf.locator('.start-recent-name')).toHaveText(['The Northern Cycle', 'Orchard Notes'])
    await resizeWindow(h, 1300, 900)
    await h.page.getByRole('textbox', { name: 'Find a project or book…' }).fill('Thaw')
    await expect(h.page.locator('.start-recent-card')).toHaveCount(1)
    await h.page.getByRole('textbox', { name: 'Find a project or book…' }).fill('')
    // A renderer restart reads the persisted shelf arrangement and backend manifest.
    await h.page.reload()
    await expect(h.page.locator('.project-shelf').first()).toHaveAttribute('aria-label', 'Working drafts')
    await expect(shelf.getByRole('button', { name: 'Open The Northern Cycle' })).toBeVisible()
    await expect(shelf.locator('.start-recent-name')).toHaveText(['The Northern Cycle', 'Orchard Notes'])
    // Migrate a library saved by the first bookshelf version, which had no order.
    await h.page.evaluate(() => {
      const saved = JSON.parse(localStorage.getItem('nl.projectLibrary.v1')!)
      delete saved.shelfOrder
      localStorage.setItem('nl.projectLibrary.v1', JSON.stringify(saved))
    })
    await h.page.reload()
    await expect(h.page.locator('.project-shelf').first()).toHaveAttribute('aria-label', 'My projects')
    await expect(shelf.locator('.start-recent-name')).toHaveText(['The Northern Cycle', 'Orchard Notes'])
    await shelf.getByRole('button', { name: 'Move shelf up', exact: true }).click()
    await shelf.getByRole('textbox', { name: 'Rename shelf Working drafts' }).fill('In revision')
    await h.page.keyboard.press('Enter')
    const renamed = h.page.getByRole('region', { name: 'In revision', exact: true })
    await expect(renamed).toBeVisible()
    await h.page.getByRole('region', { name: 'My projects', exact: true }).getByRole('button', { name: 'Move shelf up', exact: true }).click()
    await expect(h.page.locator('.project-shelf').first()).toHaveAttribute('aria-label', 'My projects')
    await h.page.locator('.project-library').evaluate((element) => { element.scrollTop = 0 })
    await h.page.screenshot({ path: 'test-results/project-library-organized.png' })
    await renamed.getByRole('button', { name: 'Remove shelf', exact: true }).click()
    await expect(h.page.getByRole('region', { name: 'My projects', exact: true }).locator('.start-recent-card')).toHaveCount(3)
    await h.page.getByRole('button', { name: 'Open The Thaw — The Northern Cycle', exact: true }).click()
    await expect.poll(() => h.page.evaluate(() => window.novalistStores.project.getState().projectName)).toBe('The Northern Cycle')
    const opened = await h.rpc<{ activeBookId: string; books: { id: string; name: string }[] }>('project/getState')
    expect(opened.books).toHaveLength(2)
    expect(opened.books.find((book) => book.id === opened.activeBookId)?.name).toBe('The Thaw')
  } finally { await h.close() }
})
