import { test, expect, _electron as electron } from '@playwright/test'
import { mkdtempSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { evaluateWhenReady } from './appReady'
import { parseDeepLink, deepLinkFromArgv } from '../src/main/deeplink'

/**
 * novalist:// links, so something outside the app can point at a place in it.
 *
 * Novalist registered only its two internal schemes, so nothing else could link
 * to a scene - not a task in a tracker, not a note in another app, not a row in
 * a spreadsheet of what still needs revising.
 */

test.describe('reading a link', () => {
  test('a well-formed link is understood', () => {
    expect(parseDeepLink('novalist://open?project=/books/salt&chapter=c1&scene=s2')).toEqual({
      project: '/books/salt',
      chapter: 'c1',
      scene: 's2'
    })
  })

  test('a project on its own is enough', () => {
    expect(parseDeepLink('novalist://open?project=/books/salt')).toEqual({
      project: '/books/salt',
      chapter: undefined,
      scene: undefined
    })
  })

  test('a scene without its chapter is dropped rather than half-followed', () => {
    // A scene id means nothing on its own, and opening the project while
    // silently ignoring half the link is the confusing outcome.
    expect(parseDeepLink('novalist://open?project=/p&scene=s2')?.scene).toBeUndefined()
  })

  test('anything not understood is refused outright', () => {
    // A link is generated by another program. Half-understanding one and
    // opening the wrong project is worse than doing nothing.
    expect(parseDeepLink('')).toBeNull()
    expect(parseDeepLink(null)).toBeNull()
    expect(parseDeepLink('not a url')).toBeNull()
    expect(parseDeepLink('https://example.com/open?project=/p')).toBeNull()
    // A verb this build does not have must not be guessed at.
    expect(parseDeepLink('novalist://destroy?project=/p')).toBeNull()
    // No project is nothing to open.
    expect(parseDeepLink('novalist://open')).toBeNull()
    expect(parseDeepLink('novalist://open?project=%20%20')).toBeNull()
  })

  test('a link is found among the other arguments a launcher passes', () => {
    // Windows and Linux deliver it as an argument to a second instance, mixed
    // in with whatever else was on the line.
    expect(
      deepLinkFromArgv(['C:/app/Novalist.exe', '--flag', 'novalist://open?project=/p'])?.project
    ).toBe('/p')
    expect(deepLinkFromArgv(['C:/app/Novalist.exe', '--flag'])).toBeNull()
    expect(deepLinkFromArgv([])).toBeNull()
  })
})

test('a link that arrives while the app is open follows it', async () => {
  test.setTimeout(120_000)

  const workDir = mkdtempSync(join(tmpdir(), 'nl-link-'))
  const env: Record<string, string> = Object.fromEntries(
    Object.entries(process.env).filter(([k, v]) => v !== undefined && k !== 'ELECTRON_RUN_AS_NODE')
  ) as Record<string, string>
  env.NOVALIST_NO_SPLASH = '1'
  env.NOVALIST_SETTINGS_DIR = join(workDir, 'settings')

  const app = await electron.launch({ args: ['out/main/index.js'], env })
  const page = await app.firstWindow()
  await expect(page.locator('.status-backend.connected')).toBeVisible({ timeout: 30_000 })

  // Two projects on disk. The app is left on the first, so following the link
  // to the second is observable rather than a no-op.
  const target = await evaluateWhenReady(page, async (parent) => {
    const rpc = window.novalistRpc
    // create takes the parent folder and makes the project inside it, so the
    // path to open is the one it reports back rather than one we assembled.
    const first = (await rpc.request('project/create', [parent, 'First', 'Book One'])) as {
      projectPath: string
    }
    const second = (await rpc.request('project/create', [parent, 'Linked', 'Book One'])) as {
      projectPath: string
    }
    const back = await rpc.request('project/open', [first.projectPath])
    window.novalistStores.project.getState().applyState(back as never)
    return second.projectPath
  }, workDir)

  await expect
    .poll(() => page.evaluate(() => window.novalistStores.project.getState().projectName))
    .toBe('First')

  // Straight through the main process, the way a second instance would.
  await app.evaluate(({ BrowserWindow }, link) => {
    BrowserWindow.getAllWindows()[0].webContents.send('novalist:deep-link', link)
  }, { project: target })

  await expect
    .poll(
      () => page.evaluate(() => window.novalistStores.project.getState().projectName),
      { timeout: 20_000 }
    )
    .toBe('Linked')

  await app.close()
})
