import { expect, test } from '@playwright/test'
import { dismissTour, launchApp, seedBook } from './harness'
import { holdMotion } from './motion'
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

async function expectFade(motion: Awaited<ReturnType<typeof holdMotion>>): Promise<void> {
  expect((await motion.evaluate(control => control.details()))
    .some(animation => animation.fading && animation.duration > 0 && animation.duration <= 200)).toBe(true)
  await motion.evaluate(control => control.finish())
}

test('Codex selection and detail tabs fade without remounting fields or animating typing', async () => {
  const h = await launchApp('nl-codex-motion-')
  try {
    await h.page.emulateMedia({ reducedMotion: 'no-preference' })
    await seedBook(h, { Opening: ['Arrival'] })
    const first = await h.rpc<{ id: string }>('entities/create', ['character', 'Mira'])
    await h.rpc('entities/create', ['character', 'Tomas'])
    await dismissTour(h.page)
    await h.page.evaluate(async id => {
      window.novalistStores.shell.getState().setMainView('codex')
      await window.novalistStores.codex.getState().select(id)
    }, first.id)
    const detail = h.page.locator('.codex-detail')
    await expect(detail.locator('h2')).toHaveText('Mira')
    await expect.poll(() => detail.evaluate(element => element.getAnimations().length)).toBe(0)
    const originalDetail = await detail.evaluateHandle(element => element)
    const motion = await holdMotion(h.page, '.codex-detail')
    await h.page.locator('.codex-row').filter({ hasText: 'Tomas' }).click()
    await expect(detail.locator('h2')).toHaveText('Tomas')
    await expectFade(motion)
    const name = detail.getByRole('textbox', { name: 'Name', exact: true })
    const originalField = await name.evaluateHandle(element => element)
    await detail.locator('.codex-entry-tabs').getByRole('button', { name: 'Story', exact: true }).click()
    await expect(detail).toHaveAttribute('data-detail-tab', 'story')
    await expectFade(motion)
    await detail.locator('.codex-entry-tabs').getByRole('button', { name: 'Overview', exact: true }).click()
    await expectFade(motion)
    expect(await originalDetail.evaluate(element => element.isConnected)).toBe(true)
    expect(await originalField.evaluate(element => element.isConnected)).toBe(true)
    await name.fill('Tomas Vance')
    await expect(name).toBeFocused()
    expect((await motion.evaluate(control => control.details())).some(animation => animation.fading)).toBe(false)
    await motion.evaluate(control => control.stop())
    await h.page.emulateMedia({ reducedMotion: 'reduce' })
    await detail.locator('.codex-entry-tabs').getByRole('button', { name: 'Details', exact: true }).click()
    await expect(detail).toHaveAttribute('data-detail-tab', 'details')
    expect(await detail.evaluate(element => element.getAnimations({ subtree: true }).length)).toBe(0)
  } finally {
    await h.close()
  }
})

test('Research selection and scratchpad tabs fade while preserving and saving the note', async () => {
  const h = await launchApp('nl-research-motion-')
  try {
    await h.page.emulateMedia({ reducedMotion: 'no-preference' })
    await seedBook(h, { Opening: ['Arrival'] })
    await h.rpc('research/save', [null, 'First source', 'Note', 'First note.', [], []])
    await h.rpc('research/save', [null, 'Second source', 'Note', 'Second note.', [], []])
    await dismissTour(h.page)
    await h.page.evaluate(() => window.novalistStores.shell.getState().setMainView('research'))
    const view = h.page.locator('.research-view')
    await view.locator('.codex-row').filter({ hasText: 'First source' }).click()
    const title = view.getByRole('textbox', { name: 'Title', exact: true })
    await expect(title).toHaveValue('First source')
    await expect.poll(() => view.evaluate(element => element.getAnimations({ subtree: true }).length)).toBe(0)
    const motion = await holdMotion(h.page, '.research-view')
    await view.locator('.codex-row').filter({ hasText: 'Second source' }).click()
    await expect(title).toHaveValue('Second source')
    await expectFade(motion)
    const originalEditor = await title.evaluateHandle(element => element)
    await title.fill('Edited second source')
    expect((await motion.evaluate(control => control.details())).some(animation => animation.fading)).toBe(false)
    const tabs = view.locator('.codex-tabs .codex-tab')
    await tabs.nth(1).click()
    await expect(view.locator('.research-scratchpad')).toBeVisible()
    await expectFade(motion)
    await tabs.nth(0).click()
    await expect(title).toHaveValue('Edited second source')
    await expectFade(motion)
    expect(await originalEditor.evaluate(element => element.isConnected)).toBe(true)
    await expect.poll(() => h.rpc<{ title: string }[]>('research/list'))
      .toEqual(expect.arrayContaining([expect.objectContaining({ title: 'Edited second source' })]))
    await motion.evaluate(control => control.stop())
  } finally {
    await h.close()
  }
})

test('Calendar modes fade and go-to disclosure closes inert with keyboard focus restored', async () => {
  const h = await launchApp('nl-calendar-motion-')
  try {
    await h.page.emulateMedia({ reducedMotion: 'no-preference' })
    await seedBook(h, { Opening: ['Arrival'] })
    await dismissTour(h.page)
    await h.page.evaluate(() => window.novalistStores.shell.getState().setMainView('calendar'))
    const view = h.page.locator('.calendar')
    await expect(view.locator('.calendar-month')).toBeVisible()
    await expect.poll(() => view.evaluate(element => element.getAnimations({ subtree: true }).length)).toBe(0)
    const motion = await holdMotion(h.page, '.calendar')
    await view.getByRole('button', { name: 'Week', exact: true }).click()
    await expect(view.locator('.calendar-week-grid')).toBeVisible()
    await expectFade(motion)
    const open = view.getByRole('button', { name: 'Go to date', exact: true })
    await open.click()
    const input = view.getByRole('textbox', { name: 'Go to date', exact: true })
    await expect(input).toBeFocused()
    await expectFade(motion)
    await input.press('Escape')
    const presence = view.locator('[data-motion-presence]').filter({ has: h.page.locator('#calendar-go-to') })
    await expect(presence).toHaveAttribute('data-motion-presence', 'closing')
    await expect(presence).toHaveAttribute('inert', '')
    await expect(open).toBeFocused()
    await expectFade(motion)
    await expect(view.locator('#calendar-go-to')).toHaveCount(0)
    await motion.evaluate(control => control.stop())
    await h.page.emulateMedia({ reducedMotion: 'reduce' })
    await view.getByRole('button', { name: 'Year', exact: true }).click()
    await expect(view.locator('.calendar-year')).toBeVisible()
    expect(await view.evaluate(element => element.getAnimations({ subtree: true }).length)).toBe(0)
  } finally {
    await h.close()
  }
})

test('Wiki selection fades when the requested article arrives', async () => {
  const h = await launchApp('nl-wiki-motion-')
  try {
    await h.page.emulateMedia({ reducedMotion: 'no-preference' })
    await seedBook(h, { Opening: ['Arrival'] })
    await h.rpc('entities/create', ['character', 'Mira'])
    await h.rpc('entities/create', ['character', 'Tomas'])
    await dismissTour(h.page)
    await h.page.evaluate(() => window.novalistStores.shell.getState().setMainView('wiki'))
    await h.page.locator('.wiki-entry').filter({ hasText: 'Mira' }).click()
    const article = h.page.locator('.wiki-main')
    await expect(article.locator('h1')).toHaveText('Mira')
    await expect.poll(() => article.evaluate(element => element.getAnimations().length)).toBe(0)
    const motion = await holdMotion(h.page, '.wiki-main')
    await h.page.locator('.wiki-entry').filter({ hasText: 'Tomas' }).click()
    await expect(article.locator('h1')).toHaveText('Tomas')
    await expectFade(motion)
    await motion.evaluate(control => control.stop())
  } finally {
    await h.close()
  }
})

test('Gallery layout and lightbox animate while native Escape restores focus immediately', async () => {
  const h = await launchApp('nl-gallery-motion-')
  try {
    await h.page.emulateMedia({ reducedMotion: 'no-preference' })
    await seedBook(h, { Opening: ['Arrival'] })
    const source = join(h.workDir, 'reference.png')
    writeFileSync(source, Buffer.from(
      'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aZAAAAABJRU5ErkJggg==',
      'base64'
    ))
    await h.rpc('gallery/import', [source])
    await dismissTour(h.page)
    await h.page.evaluate(() => window.novalistStores.shell.getState().setMainView('gallery'))
    const gallery = h.page.locator('.gallery')
    await expect(gallery.locator('.gallery-item')).toBeVisible()
    await expect.poll(() => gallery.evaluate(element => element.getAnimations({ subtree: true }).length)).toBe(0)
    const motion = await holdMotion(h.page, '.gallery')
    await gallery.locator('.gallery-viewtoggle-btn').nth(1).click()
    const row = gallery.locator('.gallery-list-row')
    await expect(row).toBeVisible()
    await expectFade(motion)
    await row.focus()
    await row.press('Enter')
    const lightbox = gallery.locator('.gallery-lightbox')
    await expect(lightbox).toHaveAttribute('open', '')
    await expectFade(motion)
    await h.page.keyboard.press('Escape')
    const presence = gallery.locator('[data-motion-presence]').filter({ has: h.page.locator('.gallery-lightbox') })
    await expect(presence).toHaveAttribute('inert', '')
    await expect(lightbox).not.toHaveAttribute('open', '')
    await expect(row).toBeFocused()
    await expectFade(motion)
    await expect(lightbox).toHaveCount(0)
    await row.click({ button: 'right' })
    await expect(gallery.locator('.gallery-menu')).toBeVisible()
    await expectFade(motion)
    await gallery.locator('.gallery-menu-scrim').click({ position: { x: 2, y: 2 } })
    await expectFade(motion)
    await expect(gallery.locator('.gallery-menu')).toHaveCount(0)
    await motion.evaluate(control => control.stop())
  } finally {
    await h.close()
  }
})

test('Map layer branches collapse smoothly and retain nested expansion choices', async () => {
  const h = await launchApp('nl-map-tree-motion-')
  try {
    await h.page.emulateMedia({ reducedMotion: 'no-preference' })
    await seedBook(h, { Opening: ['Arrival'] })
    await h.rpc('maps/create', ['Coast'])
    await dismissTour(h.page)
    await h.page.evaluate(() => window.novalistStores.shell.getState().setMainView('maps'))
    const tree = h.page.locator('.map-layer-tree')
    const rows = tree.locator('.map-layer-row')
    await h.page.locator('.map-panel-add').click()
    await expect(rows).toHaveCount(1)
    await rows.first().locator('.map-layer-actions button').nth(2).click()
    await expect(rows).toHaveCount(2)
    await rows.nth(1).locator('.map-layer-actions button').nth(2).click()
    await expect(rows).toHaveCount(3)
    await expect.poll(() => tree.evaluate(element => element.getAnimations({ subtree: true }).length)).toBe(0)
    const motion = await holdMotion(h.page, '.map-layer-tree')
    const descendant = rows.nth(2).locator('..')
    const expandedHeight = await descendant.evaluate(element => element.getBoundingClientRect().height)
    await rows.nth(1).locator('.map-layer-twisty').click()
    const closing = tree.locator('[data-motion-presence="closing"][inert]')
    await expect(closing).toHaveCount(1)
    await motion.evaluate(control => control.middle())
    const height = await descendant.evaluate(element => element.getBoundingClientRect().height)
    expect(height).toBeGreaterThan(0)
    expect(height).toBeLessThan(expandedHeight)
    await expectFade(motion)
    await expect(rows).toHaveCount(2)
    await rows.first().locator('.map-layer-twisty').click()
    await expect(closing).toHaveCount(2)
    await expectFade(motion)
    await expect(rows).toHaveCount(1)
    await rows.first().locator('.map-layer-twisty').click()
    await expectFade(motion)
    await expect(rows).toHaveCount(2)
    await rows.nth(1).locator('.map-layer-twisty').click()
    await expectFade(motion)
    await expect(rows).toHaveCount(3)
    await motion.evaluate(control => control.stop())
    await h.page.emulateMedia({ reducedMotion: 'reduce' })
    await rows.first().locator('.map-layer-twisty').click()
    await expect(rows).toHaveCount(1)
    expect(await tree.evaluate(element => element.getAnimations({ subtree: true }).length)).toBe(0)
  } finally {
    await h.close()
  }
})
