from pathlib import Path
import hashlib,json,subprocess
w=Path(__file__).parent;s=json.loads((w/'private-state.json').read_text());sim=s['simulator'];main=Path('<repository>')
h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def tree(p):return {str(f.relative_to(p)):h(f) for f in sorted(p.rglob('*')) if f.is_file()}
def container(bundle,kind):return Path(subprocess.check_output(['xcrun','simctl','get_app_container',sim,bundle,kind],text=True).strip())
data=container('com.novalist.app','data');installed=container('com.novalist.app','app');before=json.loads((w/'documents-before.json').read_text());original=json.loads(Path('<private-r15-workspace>/before.json').read_text());assert all((data/'Documents'/p).is_file() and h(data/'Documents'/p)==v for p,v in original['documents'].items())
assert all((data/'Documents'/p).is_file() and h(data/'Documents'/p)==v for p,v in before.items())
local=data/'Documents'/s['name'];external=Path(s['external_path']);assert tree(local)==json.loads((w/'local-before-unavailable.json').read_text());assert tree(external)==json.loads((w/'external-before-unavailable.json').read_text());assert not (data/'Documents/NovalistAudit').exists()
assert tree(installed)==json.loads((w/'clean-app.json').read_text())['files']
inputs=json.loads((w/'production-inputs.json').read_text());assets=json.loads((w/'renderer-assets.json').read_text());assert all(h(main/p)==v and h(w/'checkout'/p)==v for p,v in inputs.items());assert all(h(w/'checkout/Novalist.Mobile/Resources/Raw/app'/p)==v and h(main/'Novalist.Mobile/Resources/Raw/app'/p)==v for p,v in assets.items())
reg=json.loads((data/'Library/owned-project-paths.json').read_text());recent=json.loads((data/'Library/settings.json').read_text())['recentProjects'];assert str(external) not in reg;assert str(local) in reg;assert not any(r['projectId']==s['external_id'] for r in recent);assert next(r for r in recent if r['projectId']==s['local_id'])['path']==str(local)
record={'original_fixture_files':len(original['documents']),'all_original_fixture_files_byte_identical':True,'original_documents_files':len(before),'all_original_documents_present_and_byte_identical':True,'local_synthetic_files':len(tree(local)),'all_local_synthetic_files_byte_identical_to_before_missing_operation':True,'external_synthetic_files':len(tree(external)),'all_restored_external_synthetic_files_byte_identical_to_backup':True,'observer_directory_absent':True,'installed_app_matches_clean_manifest':True,'production_inputs_match_main_and_frozen':len(inputs),'mobile_assets_match_main_and_frozen':len(assets),'external_unowned_after_clean_relaunch':True,'local_owned_after_clean_relaunch':True,'natural_external_recent_prune_retained':True,'local_recent_resolves_to_same_local_fixture':True,'clean_install_changed_app_data_container':data!=Path(s['local_path']).parents[1],'registry_scope_note':'Registry bytes were unchanged through missing resolution and fixture restoration. A later clean reinstall may add an exact alias for its new app container; this is separate from the missing-path assertion.'}
(w/'preservation.json').write_text(json.dumps(record,indent=2)+'\n');print(json.dumps(record))
