from pathlib import Path
import subprocess,json,shutil,uuid,hashlib
sim='4E5429FE-834B-4B50-8BBF-680A2914C06D'
def container(bundle):return Path(subprocess.check_output(['xcrun','simctl','get_app_container',sim,bundle,'data'],text=True).strip())
app=container('com.novalist.app');provider=container('com.novalist.audit.fixtures');source=provider/'Documents/MovedParent/Audit Project A';external=provider/'Documents/Audit Matching Suffix';assert not external.exists();shutil.copytree(source,external)
f=external/'.novalist/project.json';meta=json.loads(f.read_text());meta['id']='audit-external-'+uuid.uuid4().hex;meta['name']='Audit External Match';meta['books'][0]['id']='book-external-'+uuid.uuid4().hex;meta['books'][0]['name']='Audit External Book';meta['activeBookId']=meta['books'][0]['id'];f.write_text(json.dumps(meta,indent=2)+'\n')
scenes=[p for p in external.rglob('*.novalist') if p.is_file()];assert len(scenes)==1;marker='M03EXTERNAL20261007';scenes[0].write_text(scenes[0].read_text()+'\n<p>'+marker+'</p>\n')
local=app/'Documents/Audit Matching Suffix';localmeta=json.loads((local/'.novalist/project.json').read_text());registry=json.loads((app/'Library/owned-project-paths.json').read_text());assert str(local) in registry;assert str(external) not in registry;assert localmeta['id']!=meta['id'];assert local.relative_to(app/'Documents')==external.relative_to(provider/'Documents')
state={'simulator':sim,'old_app_container':str(app),'provider_container':str(provider),'external_path':str(external),'local_path':str(local),'external_id':meta['id'],'external_book_id':meta['activeBookId'],'local_id':localmeta['id'],'marker':marker};Path('/private/tmp/novalist-m03-external/private-state.json').write_text(json.dumps(state,indent=2))
hash=lambda s:hashlib.sha256(s.encode()).hexdigest();record={'source_reference':'../simulator-ui/m05-smoke/share-final-inputs.json','native_probes':False,'fixture_method':'Owned project created by native New Project with default Documents; external project copied from prior synthetic imported project, given new synthetic project/book IDs and external marker before native opening. No settings/recents/ownership registry writes by harness.','matching_documents_relative_path':'Audit Matching Suffix','different_project_ids':True,'local_project_id_sha256':hash(localmeta['id']),'external_project_id_sha256':hash(meta['id']),'external_book_id_sha256':hash(meta['activeBookId']),'external_marker_sha256':hash(marker),'local_exact_owned_entry_present':True,'external_owned_entry_absent':True,'external_project_metadata_sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'external_scene_sha256':hashlib.sha256(scenes[0].read_bytes()).hexdigest()};Path('artifacts/audit-2026-10-06/macos-validation/m03-external/01-fixture-setup.json').write_text(json.dumps(record,indent=2)+'\n');print(json.dumps(record))
