type Tr = (key: string) => string

/** Localized [value, label] pairs for the road / river spline preset picker. */
export const SPLINE_PRESETS: { kind: string; preset: string; labelKey: string }[] = [
  { kind: 'road', preset: 'motorway', labelKey: 'map.roadMotorway' },
  { kind: 'road', preset: 'primary', labelKey: 'map.roadPrimary' },
  { kind: 'road', preset: 'secondary', labelKey: 'map.roadSecondary' },
  { kind: 'road', preset: 'residential', labelKey: 'map.roadResidential' },
  { kind: 'road', preset: 'service', labelKey: 'map.roadService' },
  { kind: 'road', preset: 'pedestrian', labelKey: 'map.roadPedestrian' },
  { kind: 'road', preset: 'trail', labelKey: 'map.roadTrail' },
  { kind: 'road', preset: 'track', labelKey: 'map.roadTrack' },
  { kind: 'river', preset: 'brook', labelKey: 'map.riverBrook' },
  { kind: 'river', preset: 'stream', labelKey: 'map.riverStream' },
  { kind: 'river', preset: 'river', labelKey: 'map.riverRiver' },
  { kind: 'river', preset: 'canal', labelKey: 'map.riverCanal' },
  { kind: 'river', preset: 'estuary', labelKey: 'map.riverEstuary' }
]

export const TERRAIN_TYPES: { type: string; labelKey: string }[] = [
  { type: 'grass', labelKey: 'map.terrainGrass' },
  { type: 'forest', labelKey: 'map.terrainForest' },
  { type: 'concrete', labelKey: 'map.terrainConcrete' },
  { type: 'sand', labelKey: 'map.terrainSand' },
  { type: 'hills', labelKey: 'map.terrainHills' },
  { type: 'mountain', labelKey: 'map.terrainMountain' },
  { type: 'water', labelKey: 'map.terrainWater' }
]

export const BUILDING_TYPES: { type: string; labelKey: string }[] = [
  { type: 'singleFamily', labelKey: 'map.bldSingleFamily' },
  { type: 'rowHome', labelKey: 'map.bldRowHome' },
  { type: 'school', labelKey: 'map.bldSchool' },
  { type: 'police', labelKey: 'map.bldPolice' },
  { type: 'fireStation', labelKey: 'map.bldFireStation' },
  { type: 'hall', labelKey: 'map.bldHall' },
  { type: 'playground', labelKey: 'map.bldPlayground' },
  { type: 'trainStation', labelKey: 'map.bldTrainStation' }
]

/**
 * Builds the localized strings blob map.html's setMapStrings() consumes to drive
 * its in-canvas bottom bar, context menus, HUD and enum selects. Mirrors
 * MapView.axaml.cs PushMapStrings. Values are looked up through the same flat
 * `map.*` locale keys the Avalonia app used.
 */
const MAP_STRING_KEYS = {
    knotDelete: 'map.knotDelete',
    knotClearOverride: 'map.knotClearOverride',
    knotTypePrefix: 'map.knotTypePrefix',
    labelEditText: 'map.labelEditText',
    ctxDelete: 'map.ctxDelete',
    clipHint: 'map.clipHint',
    clipDone: 'map.clipDone',
    clipClear: 'map.clipClear',
    clipCancel: 'map.clipCancel',
    splineEditHint: 'map.splineEditHint',
    splineEditDone: 'map.splineEditDone',
    widthHandleTip: 'map.widthHandleTip',
    ctxEdit: 'map.ctxEdit',
    moveToLayer: 'map.moveToLayer',
    knotAddBefore: 'map.knotAddBefore',
    knotAddAfter: 'map.knotAddAfter',
    knotClearDirection: 'map.knotClearDirection',
    splineDelete: 'map.splineDelete',
    rotHandleTip: 'map.rotHandleTip',
    shapeDelete: 'map.shapeDelete',
    terrainEditHint: 'map.terrainEditHint',
    buildingDelete: 'map.buildingDelete',
    bldRotateTip: 'map.bldRotateTip',
    fpWall: 'map.fpWall',
    fpDoor: 'map.fpDoor',
    fpWindow: 'map.fpWindow',
    fpStairs: 'map.fpStairs',
    fpLabel: 'map.fpLabel',
    fpPin: 'map.fpPin',
    fpFlipSide: 'map.fpFlipSide',
    fpHint: 'map.fpHint',
    fpNoFloorsWarn: 'map.fpNoFloorsWarn',
    cancel: 'map.cancel',
    borderEditHint: 'map.borderEditHint',
    bbIdle: 'map.bbIdle',
    bbIdleHint: 'map.bbIdleHint',
    bb3dLabel: 'map.bb3dLabel',
    bb3dHint: 'map.bb3dHint',
    kbd3dMove: 'map.kbd3dMove',
    bbClipLabel: 'map.bbClipLabel',
    bbFloorPlanLabel: 'map.bbFloorPlanLabel',
    bbSplineLabel: 'map.bbSplineLabel',
    bbTerrainLabel: 'map.bbTerrainLabel',
    bbBorderLabel: 'map.bbBorderLabel',
    bbBuildingLabel: 'map.bbBuildingLabel',
    bbPinLabel: 'map.bbPinLabel',
    bbLabelSelLabel: 'map.bbLabelSelLabel',
    bbImageLabel: 'map.bbImageLabel',
    bbSplineDraft: 'map.bbSplineDraft',
    bbTerrainDraft: 'map.bbTerrainDraft',
    bbBorderDraft: 'map.bbBorderDraft',
    bbBuildingPlace: 'map.bbBuildingPlace',
    bbBuildingHint: 'map.bbBuildingHint',
    bbBuildingEditHint: 'map.bbBuildingEditHint',
    bbEditFloorPlan: 'map.bbEditFloorPlan',
    bbSelectedHint: 'map.bbSelectedHint',
    bbClickToAddPoints: 'map.bbClickToAddPoints',
    kbdEscCancelEnterCommit: 'map.kbdEscCancelEnterCommit',
    kbdBuildingPlace: 'map.kbdBuildingPlace',
    kbdFinishDelete: 'map.kbdFinishDelete',
    kbdFinish: 'map.kbdFinish',
    kbdEscDeselect: 'map.kbdEscDeselect',
    kbdDeleteRemoveEscDeselect: 'map.kbdDeleteRemoveEscDeselect',
    hudMap: 'map.hudMap',
    hudZoom: 'map.hudZoom',
    hudRuler: 'map.hudRuler',
    pinTargetMap: 'map.pinTargetMap',
    pinNoTargetMap: 'map.pinNoTargetMap',
    hudLayer: 'map.hudLayer',
    hudSplineDraft: 'map.hudSplineDraft',
    hudTerrainDraft: 'map.hudTerrainDraft',
    hudBorderDraft: 'map.hudBorderDraft',
    hudWallDraft: 'map.hudWallDraft',
    hudKnots: 'map.hudKnots',
    hudVerts: 'map.hudVerts',
    hudPts: 'map.hudPts',
    bbLayer: 'map.bbLayer',
    bbMore: 'map.bbMore',
    bbColors: 'map.bbColors',
    bbKnot: 'map.bbKnot',
    pinLabel: 'map.pinLabel',
    pinLabelWatermark: 'map.pinLabelWatermark',
    pinEntity: 'map.pinEntity',
    pinEntityWatermark: 'map.pinEntityWatermark',
    pinEntityNoResults: 'map.pinEntityNoResults',
    pinColor: 'map.pinColor',
    pinIcon: 'map.pinIcon',
    pinIconDot: 'map.pinIconDot',
    pinIcon_city: 'map.pinIcon_city',
    pinIcon_town: 'map.pinIcon_town',
    pinIcon_village: 'map.pinIcon_village',
    pinIcon_castle: 'map.pinIcon_castle',
    pinIcon_tower: 'map.pinIcon_tower',
    pinIcon_ruin: 'map.pinIcon_ruin',
    pinIcon_temple: 'map.pinIcon_temple',
    pinIcon_mountain: 'map.pinIcon_mountain',
    pinIcon_hills: 'map.pinIcon_hills',
    pinIcon_forest: 'map.pinIcon_forest',
    pinIcon_lake: 'map.pinIcon_lake',
    pinIcon_port: 'map.pinIcon_port',
    pinIcon_bridge: 'map.pinIcon_bridge',
    pinIcon_mine: 'map.pinIcon_mine',
    pinIcon_camp: 'map.pinIcon_camp',
    pinIcon_crossroads: 'map.pinIcon_crossroads',
    pinIcon_cave: 'map.pinIcon_cave',
    pinIcon_battle: 'map.pinIcon_battle',
    labelFontSize: 'map.labelFontSize',
    labelColor: 'map.labelColor',
    alignLeft: 'map.alignLeft',
    alignCenter: 'map.alignCenter',
    alignRight: 'map.alignRight',
    shapeType: 'map.shapeType',
    shapeColor: 'map.shapeColor',
    shapeSmooth: 'map.shapeSmooth',
    shapeBlend: 'map.shapeBlend',
    shapeForward: 'map.shapeForward',
    shapeBackward: 'map.shapeBackward',
    buildingType: 'map.buildingType',
    buildingRoof: 'map.buildingRoof',
    buildingFloors: 'map.buildingFloors',
    buildingPlanZoom: 'map.buildingPlanZoom',
    roofPitch: 'map.roofPitch',
    splineType: 'map.splineType',
    splineClosed: 'map.splineClosed',
    splineMarking: 'map.splineMarking',
    splineBlend: 'map.splineBlend',
    knotSharpness: 'map.knotSharpness',
    colorCasing: 'map.colorCasing',
    colorFill: 'map.colorFill',
    colorMarking: 'map.colorMarking',
    colorReset: 'map.colorReset',
    borderOutlineColor: 'map.borderOutlineColor',
    borderOutlineWidth: 'map.borderOutlineWidth',
    borderClear: 'map.borderClear',
    clip: 'map.imageMenuClip',
    imageMinZoom: 'map.imageMinZoom',
    imageMaxZoom: 'map.imageMaxZoom'
}

export function buildMapStrings(t: Tr): string {
  const pairs = <T extends { labelKey: string }>(list: T[], value: (item: T) => string): string =>
    JSON.stringify(list.map((item) => [value(item), t(item.labelKey)]))
  const strings: Record<string, string> = {
    ...Object.fromEntries(Object.entries(MAP_STRING_KEYS).map(([key, label]) => [key, t(label)])),
    buildingTypesJson: pairs(BUILDING_TYPES, (i: { type: string }) => i.type),
    roofKindsJson: JSON.stringify([
      ['gable', t('map.roofGable')],
      ['hip', t('map.roofHip')],
      ['flat', t('map.roofFlat')]
    ]),
    terrainTypesJson: pairs(TERRAIN_TYPES, (i: { type: string }) => i.type),
    splinePresetsJson: JSON.stringify(
      SPLINE_PRESETS.map((p) => [`${p.kind}:${p.preset}`, t(p.labelKey)])
    ),
    markingStylesJson: JSON.stringify([
      ['', t('map.markPresetDefault')],
      ['none', t('map.markNone')],
      ['single', t('map.markSingle')],
      ['dashed', t('map.markDashed')],
      ['double', t('map.markDouble')],
      ['solid-dashed', t('map.markSolidDashed')]
    ]),
    knotTypesJson: JSON.stringify([
      ['', t('map.knotClearType')],
      ['motorway', t('map.roadMotorway')],
      ['primary', t('map.roadPrimary')],
      ['secondary', t('map.roadSecondary')],
      ['residential', t('map.roadResidential')],
      ['service', t('map.roadService')],
      ['pedestrian', t('map.roadPedestrian')],
      ['trail', t('map.roadTrail')],
      ['track', t('map.roadTrack')],
      ['brook', t('map.riverBrook')],
      ['stream', t('map.riverStream')],
      ['river', t('map.riverRiver')],
      ['canal', t('map.riverCanal')],
      ['estuary', t('map.riverEstuary')]
    ]),

  }
  return JSON.stringify(strings)
}
