const assert = require('node:assert/strict');
const { writeFileSync } = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { chromium } = require('../../app/node_modules/@playwright/test');

(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const errors = [];
  const requests = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (/^https?:/.test(request.url())) requests.push(request.url()); });
  await page.goto(pathToFileURL(path.join(__dirname, 'audit.html')).href);
  assert.equal(await page.locator('.finding').count(), 73);
  assert.equal(await page.locator('.finding:visible').count(), 73);
  await page.screenshot({ path: path.join(__dirname, 'report-desktop.png') });
  await page.getByRole('button', { name: 'P1 first', exact: true }).click();
  assert.equal(await page.locator('.finding:visible').count(), 21);
  await page.getByRole('button', { name: 'Reproduced only', exact: true }).click();
  assert.equal(await page.locator('.finding:visible').count(), 30);
  await page.getByRole('button', { name: 'Mobile', exact: true }).click();
  assert.equal(await page.locator('.finding:visible').count(), 36);
  await page.getByRole('button', { name: 'Reset filters', exact: true }).click();
  await page.locator('#search').fill('no-such-finding-123');
  assert.equal(await page.locator('.finding:visible').count(), 0);
  assert.equal(await page.locator('#empty').isVisible(), true);
  await page.locator('#search').fill('A12');
  assert.equal(await page.locator('.finding:visible').count(), 1);
  await page.getByRole('button', { name: 'Expand visible', exact: true }).click();
  assert.equal(await page.locator('#A12').getAttribute('open'), '');
  const downloadReady = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download visible JSON', exact: true }).click();
  const download = await downloadReady;
  const stream = await download.createReadStream();
  const chunks = [];
  for await (const chunk of stream) chunks.push(chunk);
  const selected = JSON.parse(Buffer.concat(chunks).toString());
  assert.deepEqual(selected.findings.map(f => f.id), ['A12']);
  await page.evaluate(() => { location.hash = 'M01'; });
  await page.waitForFunction(() => document.getElementById('M01').open);
  assert.equal(await page.locator('.finding:visible').count(), 73);
  const invalidAnchors = await page.evaluate(() => Array.from(document.querySelectorAll('a[href^="#"]')).map(a => a.getAttribute('href').slice(1)).filter(id => !document.getElementById(id)));
  assert.deepEqual(invalidAnchors, []);
  await page.getByRole('button', { name: 'Collapse all', exact: true }).click();
  await page.evaluate(() => window.dispatchEvent(new Event('beforeprint')));
  assert.equal(await page.locator('.finding[open]').count(), 73);
  await page.evaluate(() => window.dispatchEvent(new Event('afterprint')));
  assert.equal(await page.locator('.finding[open]').count(), 0);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => { location.hash = ''; window.scrollTo(0, 0); });
  await page.screenshot({ path: path.join(__dirname, 'report-mobile.png') });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1), false);
  await page.locator('#A01 summary').click();
  await page.locator('#A01').scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(__dirname, 'report-finding-mobile.png') });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1), false);
  assert.deepEqual(errors, []);
  assert.deepEqual(requests, []);
  await browser.close();
  writeFileSync(path.join(__dirname, 'report-validation.json'), JSON.stringify({ result: 'passed', findings: 73, checks: ['all counts', 'priority filter', 'evidence filter', 'mobile filter', 'search/no results', 'expand/collapse', 'filtered JSON download', 'deep links', 'internal anchors', 'print expansion/restoration', '390px layout', 'no horizontal overflow', 'no JS errors', 'no network dependencies'] }, null, 2));
  console.log('Report validation passed. Desktop/mobile screenshots saved.');
})().catch(error => { console.error(error); process.exitCode = 1; });
